version: "3.8"

services:
  frontend:
    image: gayathri0315/mean-frontend:latest
    container_name: mean_frontend
    restart: always

  backend:
    image: gayathri0315/mean-backend:latest
    container_name: mean_backend
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/tutorials_db

  mongo:
    image: mongo:6.0
    container_name: mean_mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: mean_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo-data:
